import { Achievement } from '../../types/achievements';

export const initialAchievements: Achievement[] = [
  {
    id: 'first_boot',
    code: 'FIRST_BOOT',
    title: 'First Boot Initialized',
    description: 'Successfully initialized SAKETH.OS workstation kernel and mounted the virtual filesystem.',
    hint: 'Boot into the operating system.',
    category: 'discovery',
    isSecret: false,
    unlocked: true,
    unlockedAt: '2026-09-08',
    xp: 50,
    iconName: 'Power'
  },
  {
    id: 'explorer',
    code: 'EXPLORER',
    title: 'Repository Explorer',
    description: 'Explored project repositories, traversed virtual filesystem trees, and inspected system specs.',
    hint: 'Explore projects with "projects" or inspect hardware with "neofetch".',
    category: 'discovery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 75,
    iconName: 'Folder'
  },
  {
    id: 'builder',
    code: 'BUILDER',
    title: 'Architect & Builder',
    description: 'Explored flagship production projects, source specifications, and engineering trade-offs.',
    hint: 'Navigate project directories with "projects" or "cd projects/weavly".',
    category: 'projects',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Layers'
  },
  {
    id: 'hackathon',
    code: 'HACKATHON',
    title: 'Hackathon Champion (Amaravati & National AI)',
    description: '2nd Prize at Amaravati Quantum Valley Hackathon (BB84 QKD E-Auction) & 2nd Prize at National AI Hackathon (Automated Evaluation System).',
    hint: 'Explore achievements with "achievements" or "git log".',
    category: 'mastery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 150,
    iconName: 'Award'
  },
  {
    id: 'ship_it',
    code: 'SHIP_IT',
    title: 'Production Scale Master',
    description: 'Inspected high-throughput distributed systems metrics (1.8B+ events, sub-50ms p99 vector latency).',
    hint: 'Inspect project metrics with "cat projects/weavly/metrics.json" or project detail tabs.',
    category: 'mastery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Zap'
  },
  {
    id: 'system_architect',
    code: 'SYSTEM_ARCHITECT',
    title: 'System Architect',
    description: 'Inspected system architecture topologies, data flow diagrams, and architectural trade-offs.',
    hint: 'View architecture in projects with "cat projects/weavly/architecture/system-design.md".',
    category: 'projects',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 120,
    iconName: 'Cpu'
  },
  {
    id: 'root_access',
    code: 'CLASSIFIED',
    title: 'Classified Executive Dossier',
    description: 'Elevated privileges with "sudo make-me-hireable" and unlocked the candidate assessment matrix.',
    hint: 'Execute superuser candidate command in terminal: "sudo make-me-hireable".',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 200,
    iconName: 'ShieldAlert'
  },
  {
    id: 'matrix_rain',
    code: 'MATRIX_RAIN',
    title: 'Follow the White Rabbit',
    description: 'Activated the terminal digital phosphor rain matrix animation.',
    hint: 'Enter the Matrix.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 150,
    iconName: 'Terminal'
  },
  {
    id: 'konami_code',
    code: 'KONAMI_CODE',
    title: 'Retro Gamer Code',
    description: 'Entered the legendary Konami code (↑ ↑ ↓ ↓ ← → ← → B A) on the keyboard.',
    hint: 'Classic 8-bit cheat code sequence.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 250,
    iconName: 'Gamepad2'
  },
  {
    id: 'system_auditor',
    code: 'SYSTEM_AUDITOR',
    title: 'Zero-Day Security Audit',
    description: 'Executed terminal security audit scan to verify zero vulnerabilities.',
    hint: 'Try the "hack" command.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Lock'
  },
  {
    id: 'philosopher',
    code: 'PHILOSOPHER',
    title: 'Unix Philosophy',
    description: 'Queried the terminal oracle for software engineering wisdom.',
    hint: 'Run "fortune" or "quote".',
    category: 'discovery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 50,
    iconName: 'BookOpen'
  },
  {
    id: 'speed_demon',
    code: 'SPEED_DEMON',
    title: 'Keyboard Maestro',
    description: 'Navigated terminal efficiently using Tab autocomplete or history recall.',
    hint: 'Use Tab for autocompletion or ↑/↓ for command history.',
    category: 'discovery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 75,
    iconName: 'Command'
  }
];
