import { Achievement } from '../../types/achievements';

export const initialAchievements: Achievement[] = [
  {
    id: 'first_boot',
    code: 'FIRST_BOOT',
    title: 'First Boot Initialized',
    description: 'Successfully initialized SAKETH.OS workstation kernel and mounted the virtual filesystem.',
    hint: 'Boot into the operating system.',
    category: 'discovery',
    isSecret: false,
    unlocked: true,
    unlockedAt: '2026-09-08',
    xp: 50,
    iconName: 'Power'
  },
  {
    id: 'builder',
    code: 'BUILDER',
    title: 'Architect & Builder',
    description: 'Explored flagship production projects, system architecture diagrams, and engineering trade-offs.',
    hint: 'Navigate project directories with "projects" or "cd projects/weavly".',
    category: 'projects',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Layers'
  },
  {
    id: 'hackathon',
    code: 'HACKATHON',
    title: 'Quantum Valley Hackathon',
    description: 'Discovered the 1st Place AI Hackathon victory and multimodal vision pipeline milestone.',
    hint: 'Explore Git career history with "git log" or "git show 91be72a".',
    category: 'mastery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 150,
    iconName: 'Award'
  },
  {
    id: 'ship_it',
    code: 'SHIP_IT',
    title: 'Production Scale Master',
    description: 'Inspected high-throughput distributed systems metrics (1.8B+ events, sub-50ms p99 vector latency).',
    hint: 'Inspect project metrics with "cat projects/weavly/metrics.json" or project detail tabs.',
    category: 'mastery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Zap'
  },
  {
    id: 'root_access',
    code: 'ROOT_ACCESS',
    title: 'Root Elevation (Sudo)',
    description: 'Elevated privileges with "sudo make-me-hireable" and unlocked the executive candidate briefing.',
    hint: 'Execute superuser command in terminal.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 200,
    iconName: 'ShieldAlert'
  },
  {
    id: 'deep_dive',
    code: 'DEEP_DIVE',
    title: 'Telemetry Deep Dive',
    description: 'Inspected technology capabilities, architecture concepts, and associated projects in the Stack Matrix.',
    hint: 'Run "skills" or "inspect spring-boot".',
    category: 'system',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Cpu'
  },
  {
    id: 'matrix_rain',
    code: 'MATRIX_RAIN',
    title: 'Follow the White Rabbit',
    description: 'Activated the terminal digital phosphor rain matrix animation.',
    hint: 'Enter the Matrix.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 150,
    iconName: 'Terminal'
  },
  {
    id: 'konami_code',
    code: 'KONAMI_CODE',
    title: 'Retro Gamer Code',
    description: 'Entered the legendary Konami code (↑ ↑ ↓ ↓ ← → ← → B A) on the keyboard.',
    hint: 'Classic 8-bit cheat code sequence.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 250,
    iconName: 'Gamepad2'
  },
  {
    id: 'system_auditor',
    code: 'SYSTEM_AUDITOR',
    title: 'Zero-Day Security Audit',
    description: 'Executed terminal security audit scan to verify zero vulnerabilities.',
    hint: 'Try the "hack" command.',
    category: 'secrets',
    isSecret: true,
    unlocked: false,
    unlockedAt: null,
    xp: 100,
    iconName: 'Lock'
  },
  {
    id: 'explorer',
    code: 'EXPLORER',
    title: 'Hardware & OS Telemetry',
    description: 'Inspected developer workstation hardware, kernel specs, and color palette with neofetch.',
    hint: 'Run "neofetch" or "sysinfo".',
    category: 'system',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 75,
    iconName: 'Monitor'
  },
  {
    id: 'philosopher',
    code: 'PHILOSOPHER',
    title: 'Unix Philosophy',
    description: 'Queried the terminal oracle for software engineering wisdom.',
    hint: 'Run "fortune" or "quote".',
    category: 'discovery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 50,
    iconName: 'BookOpen'
  },
  {
    id: 'speed_demon',
    code: 'SPEED_DEMON',
    title: 'Keyboard Maestro',
    description: 'Navigated terminal efficiently using Tab autocomplete or history recall.',
    hint: 'Use Tab for autocompletion or ↑/↓ for command history.',
    category: 'discovery',
    isSecret: false,
    unlocked: false,
    unlockedAt: null,
    xp: 75,
    iconName: 'Command'
  }
];
